import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import io
import os

# ==========================================
# 1. LOAD DATA
# ==========================================
# Assuming the file is generated by the V41 simulation script
FILE_INPUT = "results_v41_omni_suite_2.csv"

# Output image filenames
FILE_CHART_RATE = "chart_v41_detection_omni_2.png"
FILE_CHART_HEATMAP = "chart_v41_heatmap_omni_2.png"

# Full Mapping for ALL 14 Metamorphic Relations
mr_mapping = {
    "Efficient_MR_1_Rate": "MR1: Symmetry",
    "Efficient_MR_2_Rate": "MR2: Identity",
    "Efficient_MR_3_Rate": "MR3: Negation Inv.",
    "Efficient_MR_4_Rate": "MR4: Shift Inv.",
    "Efficient_MR_5_Rate": "MR5: Periodicity",
    "Efficient_MR_6_Rate": "MR6: Feature Rot.",
    "Efficient_MR_7_Rate": "MR7: Permutation Inv.",
    "Efficient_MR_8_Rate": "MR8: Bit Inversion",
    "Efficient_MR_9_Rate": "MR9: Noise Stability",
    "Efficient_MR_10_Rate": "MR10: Feat. Sensitivity",
    "Efficient_MR_11_Rate": "MR11: Linear Scaling",
    "Efficient_MR_12_Rate": "MR12: Structural Ortho",
    "Efficient_MR_13_Rate": "MR13: Dual Consistency",
    "Efficient_MR_14_Rate": "MR14: Qubit Permutation"
}

# [NEW] Explicit Order to match Report Section 5.3 Classification
# Group A: General Mathematical (1, 2, 7)
# Group B: Quantum-Specific (12, 14, 9)
# Group C: Feature-Embedding Specific (5, 4, 8, 11, 3, 6, 10, 13)
ORDERED_MR_KEYS = [
    "Efficient_MR_1_Rate", "Efficient_MR_2_Rate", "Efficient_MR_7_Rate",  # Group A
    "Efficient_MR_12_Rate", "Efficient_MR_14_Rate", "Efficient_MR_9_Rate", # Group B
    "Efficient_MR_5_Rate", "Efficient_MR_4_Rate", "Efficient_MR_8_Rate",   # Group C (Angle/Basis)
    "Efficient_MR_11_Rate",                                                # Group C (Amp)
    "Efficient_MR_3_Rate", "Efficient_MR_6_Rate", "Efficient_MR_10_Rate", "Efficient_MR_13_Rate" # Group C (Hybrid)
]

def generate_v41_plots():
    # 1. Check if file exists
    if not os.path.exists(FILE_INPUT):
        print(f"Error: '{FILE_INPUT}' not found.")
        print("Please ensure the V41 simulation has completed successfully.")
        return

    # 2. Load Data
    print(f"Loading Omni-Suite data from {FILE_INPUT}...")
    try:
        df = pd.read_csv(FILE_INPUT)
    except Exception as e:
        print(f"Error reading CSV: {e}")
        return

    # Setup Visual Theme
    sns.set_theme(style="white", context="talk")
    modes_order = ["basis", "angle", "amplitude"]

    # ==========================================
    # 3. PLOT 1: DETECTION CONFIDENCE (Bar Chart)
    # ==========================================
    print("Generating Detection Confidence Chart...")
    plt.figure(figsize=(12, 6))

    # Calculate mean detection rate per mode
    detection_stats = df.groupby('Mode')['Caught_Rate'].mean() * 100
    detection_stats = detection_stats.reindex(modes_order, fill_value=0)

    ax1 = sns.barplot(
        x=detection_stats.index, 
        y=detection_stats.values, 
        palette="viridis",
        edgecolor="black",
        linewidth=1.5
    )

    plt.title("Statistical Detection Confidence", fontsize=18, pad=20, weight='bold')
    plt.ylabel("Avg. Detection Probability (%)", fontsize=14)
    plt.xlabel("Embedding Mode", fontsize=14)
    plt.ylim(0, 115)

    # Add labels
    for p in ax1.patches:
        ax1.annotate(
            f'{p.get_height():.1f}%', 
            (p.get_x() + p.get_width() / 2., p.get_height()),
            ha='center', va='center', 
            xytext=(0, 12), 
            textcoords='offset points', 
            weight='bold',
            fontsize=14
        )

    plt.tight_layout()
    plt.savefig(FILE_CHART_RATE, dpi=300)
    print(f"Saved: {FILE_CHART_RATE}")
    plt.close()

    # ==========================================
    # 4. PLOT 2: OMNI-SUITE HEATMAP
    # ==========================================
    print("Generating Omni-Suite Heatmap...")
    
    # [MODIFIED] Filter and Sort columns based on the new Report Groups
    # We only take columns that exist in the CSV, but we enforce the ORDER from ORDERED_MR_KEYS
    present_mr_cols = [col for col in ORDERED_MR_KEYS if col in df.columns]

    if present_mr_cols:
        # Calculate mean efficiency per mode
        heatmap_data = df.groupby('Mode')[present_mr_cols].mean() * 100
        heatmap_data = heatmap_data.reindex(modes_order, fill_value=0)
        
        # Rename columns using the mapping
        heatmap_data.columns = [mr_mapping[c] for c in heatmap_data.columns]
        
        # Large Figure for 14 Columns
        plt.figure(figsize=(20, 12)) # [MODIFIED] Slightly taller to accommodate labels
        
        # 'rocket_r' colormap: Light = Low, Dark/Black = High Efficiency
        ax = sns.heatmap(
            heatmap_data.T, 
            annot=True, 
            cmap="rocket_r", 
            fmt=".0f", 
            cbar_kws={'label': 'Statistical Reliability (%)'},
            linewidths=0,
            annot_kws={"size": 11, "weight": "bold"}
        )
        ax.grid(False)

        ax2 = ax.twinx()
        ax2.set_ylim(ax.get_ylim())
        ax2.set_yticks([1.5, 4.5, 10]) # Approximate centers of groups
        ax2.set_yticklabels(["Group A\n(General)", "Group B\n(Quantum)", "Group C\n(Embedding)"], 
                            fontsize=12, weight='bold', color='#333333')
        ax2.tick_params(right=False) # Hide ticks, keep labels

        plt.title("Metamorphic Oracle Reliability (Classified)", fontsize=18, pad=20, weight='bold')
        # [MODIFIED] Labels updated
        ax.set_xlabel("Embedding Mode", fontsize=14)

        plt.tight_layout()
        plt.savefig(FILE_CHART_HEATMAP, dpi=300)
        print(f"Saved: {FILE_CHART_HEATMAP}")
        plt.close()
    else:
        print("Warning: No MR columns found in the CSV.")

if __name__ == "__main__":
    generate_v41_plots()